databases:
  - name: fund-premium-db
    databaseName: fund_premium
    user: fund_premium_user
    plan: free

services:
  - type: web
    name: fund-premium-site
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: fund-premium-db
          property: connectionString
